### ISSUE TITLE
Suggestion - allow button names to be renamed by a response variable

### ISSUE THREAD

**Issue by HubeCubes** [kennedn/Stateful#22]
Hey there! I've really been enjoying this app, it works super smoothly and does basically everything I would like in conjunction with Home Assistant.

The only issue I have been having with this app has been figuring out how to handle items which have more than two states. In my Stateful config, I have it set up to toggle between the five inputs on my HDMI switch. Ideally, I would like the button's name to reflect the name of the input I have selected (Chromecast, Xbox, etc.). 

Cheers for designing such a great app! I am so excited to keep using it as-is-- it feels like a gamechanger.

**Comment by kennedn** [comment]
Hi Ted, I am glad you have gotten some use out of my app!

So currently the best way of achieving multi state buttons in Stateful is by creating a [Local](https://github.com/kennedn/Stateful/wiki/JSON%20Protocol#local-type) button type with multiple data entries, for example:
```
"type": 0,
"method": "PUT",
"url": "tvcom/input_select",
"headers": {},
"data": [
  {"code": "hdmi_1"},
  {"code": "hdmi_2"},
  {"code": "hdmi_3"}
]
```

This may be what you have already done? The behavior of this button type is to cycle through each data item on subsequent button presses.

As to your request, I designed the watch interactions to communicate the minimal amount of data required to function. All XHR data is stored phone side and the only pieces of information communicated to the watch app on a successful XHR request are the following:
|Variable| Type| Description|
|-----------|-------|----------------|
| Color    | Int   | An enum instructing the watch app on which color change to perform (if any)|
| Hash    | Int   |The hash value of the original request, allows the watch app to ignore 'old' XHR responses|

So as the code base stands it's not possible to dynamically switch button labels as the information isn't available watch side. The solution to this would be to allow multiple labels per button in the config menu and to refactor the way that communications work between the watch and the phone app. There are a number of side effects to this sort of change that would need worked around / considered though:
- Some buttons would likely no longer be able to be cached in the watch app due to exceeding the max storage size of 255 bytes
- The max amount of tiles per platform would be reduced significantly due to the increased average tile size. This is already quite low on Alpine (16 tiles).

Due to these considerations and the required development time for a comms refactor I am regrettably unwilling to implement it. 

Apologies,

**Comment by HubeCubes** [comment]
Thank you for the reply-- I appreciate the in-depth explanation! I am enjoying the app to its fullest as it stands. Sorry for the late response, cheers!
